// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/architecture">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/audit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/brain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/brain">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/brain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/browser-extension/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/browser-extension">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/browser-extension/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/browser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/browser">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/browser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/chronicle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/chronicle">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/chronicle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/claude-chrome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/claude-chrome">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/claude-chrome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cli-harnesses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cli-harnesses">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cli-harnesses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cloud-dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cloud-dev">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cloud-dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cloud-orchestrator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cloud-orchestrator">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cloud-orchestrator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/code">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/code/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/code/sandbox">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/code/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cold-archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cold-archive">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cold-archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/command/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/command">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/command/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/context/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/context">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/context/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/council/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/council">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/council/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/deerflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/deerflow">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/deerflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/director/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/director">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/director/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/evolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/evolution">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/evolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/healer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/healer">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/healer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/health/connectivity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/health/connectivity">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/health/connectivity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/health">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/imports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/imports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/imports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/inspector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inspector">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/inspector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/library">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/logs-metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logs-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/logs-metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/manual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manual">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/manual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/agent">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/ai-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/ai-tools">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/ai-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/always-on/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/always-on">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/always-on/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/audit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/docs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/endpoints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/endpoints">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/endpoints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/inspector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/inspector">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/inspector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/namespaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/namespaces">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/namespaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/observability">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/policies">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/registry">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/scripts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/scripts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/scripts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/search">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/system">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/tool-sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/tool-sets">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/tool-sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/tools">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mcp/tormentnexus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/tormentnexus">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mcp/tormentnexus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/memory-search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/memory-search">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/memory-search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/memory/hydration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/memory/hydration">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/memory/hydration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/memory">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mesh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mesh">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mesh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/observability">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/prompts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/pulse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pulse">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/pulse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reader">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/research">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/runtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/runtime">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/runtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/security">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/session">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/sessions/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sessions/import">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/sessions/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/skills">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/squads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/squads">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/squads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/submodules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/submodules">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/submodules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/swarm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/swarm">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/swarm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tests">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/workflows">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/workshop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/workshop">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/workshop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api">> = Specific
  const handler = {} as typeof import("../../src/app/docs/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/architecture">> = Specific
  const handler = {} as typeof import("../../src/app/docs/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/tools">> = Specific
  const handler = {} as typeof import("../../src/app/docs/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../src/app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/go/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/go/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/go/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jules/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jules/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/jules/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prompts">> = Specific
  const handler = {} as typeof import("../../src/app/api/prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tools/always-on/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tools/always-on">> = Specific
  const handler = {} as typeof import("../../src/app/api/tools/always-on/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tools/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tools/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/tools/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trpc/[trpc]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trpc/[trpc]">> = Specific
  const handler = {} as typeof import("../../src/app/api/trpc/[trpc]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
